services:
  web:
    build: .
    command: gunicorn bugtracker.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bugtracker.settings
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"